/**
 * 🎭 Dados de demonstração para o preview visual (sem backend Convex).
 *
 * Consumidos pelo mock de `convex/react` (alias configurado apenas no
 * `vite.config.ts`). As chaves seguem o caminho da função no `api`
 * (ver `convex/_generated/api.ts`, que expõe `__path`).
 *
 * Objetivo: permitir a validação visual da Etapa 1 da auditoria UX —
 * inclusive os badges de status centralizados, que só renderizam com dados.
 */

const DAY = 86_400_000;
const now = Date.now();

export const DEMO_QUERIES: Record<string, unknown> = {
  // ── Manutenção ────────────────────────────────────────────────────────
  "manutencao.listarChamados": [
    {
      _id: "t1",
      equipmentId: "eq-aquecedor",
      description: "Aquecedor de 250 °C não atinge a temperatura.",
      priority: "alta",
      requesterId: "user-demo",
      status: "aberto",
      note: "Peça já disponível no almoxarifado.",
      createdAt: now - 2 * DAY,
    },
    {
      _id: "t2",
      equipmentId: "eq-phmetro",
      description: "pH-metro com leitura instável.",
      priority: "media",
      requesterId: "user-demo",
      status: "em andamento",
      createdAt: now - 5 * DAY,
    },
    {
      _id: "t3",
      equipmentId: "eq-centrifuga",
      description: "Centrífuga com vibração anormal em alta rotação.",
      priority: "alta",
      requesterId: "user-demo",
      status: "aguardando peca",
      note: "Aguardando rolamentos do fornecedor.",
      createdAt: now - 9 * DAY,
    },
    {
      _id: "t4",
      equipmentId: "eq-estufa",
      description: "Estufa: vidro da porta com trinca.",
      priority: "media",
      requesterId: "user-demo",
      status: "concluido",
      createdAt: now - 20 * DAY,
      updatedAt: now - 12 * DAY,
    },
    {
      _id: "t5",
      equipmentId: "eq-balanca",
      description: "Balança analítica — calibração fora do prazo.",
      priority: "baixa",
      requesterId: "user-demo",
      status: "cancelado",
      createdAt: now - 30 * DAY,
      updatedAt: now - 28 * DAY,
    },
  ],
  "manutencao.listarPreventivas": [
    {
      _id: "p1",
      equipmentId: "eq-capela",
      type: "Troca de filtro HEPA",
      intervalDays: 180,
      lastDate: now - 150 * DAY,
      nextDate: now + 30 * DAY,
      lastResponsibleId: "user-demo",
      lastNote: "Fluxo nominal após troca.",
      status: "programada",
      createdAt: now - 300 * DAY,
    },
    {
      _id: "p2",
      equipmentId: "eq-autoclave",
      type: "Revisão de vedações e válvulas",
      intervalDays: 90,
      lastDate: now - 100 * DAY,
      nextDate: now - 10 * DAY,
      lastResponsibleId: "user-demo",
      status: "programada",
      createdAt: now - 400 * DAY,
    },
  ],
  "manutencao.listarCalibracoes": [
    {
      _id: "c1",
      equipmentId: "eq-balanca",
      executionDate: now - 60 * DAY,
      responsibleId: "user-demo",
      result: "aprovado",
      certificateRef: "LAB-CAL-2026-0417.pdf",
      note: "Erros dentro da faixa de OIML.",
      createdAt: now - 60 * DAY,
    },
    {
      _id: "c2",
      equipmentId: "eq-phmetro",
      executionDate: now - 15 * DAY,
      responsibleId: "user-demo",
      result: "reprovado",
      note: "Eletrodo com deriva — chamado aberto.",
      createdAt: now - 15 * DAY,
    },
  ],

  // ── Insumos ───────────────────────────────────────────────────────────
  "insumos.listSupplies": [
    {
      _id: "s1",
      name: "Ácido clorídrico P.A.",
      code: "RQ-0142",
      category: "Reagente",
      brand: "Dinâmica",
      supplier: "Científica Ltda.",
      unit: "mL",
      minimumStock: 2000,
      balance: 850,
      createdAt: now - 90 * DAY,
      updatedAt: now - 3 * DAY,
      deletedAt: undefined,
    },
    {
      _id: "s2",
      name: "Luvas nitrílicas M",
      code: "EP-0031",
      category: "EPI",
      brand: "Descarpack",
      supplier: "SegLab",
      unit: "un",
      minimumStock: 100,
      balance: 40,
      createdAt: now - 120 * DAY,
      updatedAt: now - 1 * DAY,
      deletedAt: undefined,
    },
    {
      _id: "s3",
      name: "Becker 250 mL (vidro borossilicato)",
      code: "VD-0107",
      category: "Vidraria",
      brand: "Pyrex",
      unit: "un",
      minimumStock: 12,
      balance: 18,
      createdAt: now - 200 * DAY,
      updatedAt: now - 10 * DAY,
      deletedAt: undefined,
    },
    {
      _id: "s4",
      name: "Papel indicador de pH",
      code: "RQ-0200",
      category: "Reagente",
      brand: "Merck",
      unit: "un",
      minimumStock: 5,
      balance: 2,
      createdAt: now - 60 * DAY,
      updatedAt: now - 2 * DAY,
      deletedAt: undefined,
    },
  ],
  "insumos.listCategories": ["Reagente", "EPI", "Vidraria"],
  "insumos.getSupplyWithMovements": {
    supply: {
      _id: "s1",
      name: "Ácido clorídrico P.A.",
      code: "RQ-0142",
      category: "Reagente",
      brand: "Dinâmica",
      supplier: "Científica Ltda.",
      unit: "mL",
      minimumStock: 2000,
      balance: 850,
      createdAt: now - 90 * DAY,
      updatedAt: now - 3 * DAY,
      deletedAt: undefined,
    },
    movements: [
      {
        _id: "m1",
        supplyId: "s1",
        type: "entrada",
        quantity: 5000,
        lot: "L-2026-081",
        expiresAt: now + 240 * DAY,
        responsibleId: "user-demo",
        note: "Compra PO-2026-118.",
        createdAt: now - 80 * DAY,
      },
      {
        _id: "m2",
        supplyId: "s1",
        type: "saida",
        quantity: 2500,
        lot: "L-2026-081",
        responsibleId: "user-demo",
        note: "Aula de química analítica — turma 2026.1.",
        createdAt: now - 30 * DAY,
      },
      {
        _id: "m3",
        supplyId: "s1",
        type: "saida",
        quantity: 1650,
        lot: "L-2026-081",
        responsibleId: "user-demo",
        note: "Manutenção — limpeza de capela.",
        createdAt: now - 3 * DAY,
      },
    ],
  },
};
